import os

ONSHAPE_CLIENT_ID = os.environ['ONSHAPE_CLIENT_ID']
ONSHAPE_CLIENT_SECRET = os.environ['ONSHAPE_CLIENT_SECRET']
ONSHAPE_ACCESS_TOKEN_URL = os.environ['ONSHAPE_ACCESS_TOKEN_URL']
ONSHAPE_AUTHORIZE_URL = os.environ['ONSHAPE_AUTHORIZE_URL']

SECRET_KEY = "!secret"
SESSION_TYPE = 'filesystem'

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
